export const AUTH_START = "AUTH_START";
export const AUTH_GOOGLE_SUCCESS = "AUTH_GOOGLE_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const AUTH_EMAIL_SUCCESS = "AUTH_EMAIL_SUCCESS";

export const MESSAGE_FETCH_START = "MESSAGE_FETCH_START";
export const MESSAGE_FETCH_SUCCESS = "MESSAGE_FETCH_SUCCESS";
export const MESSAGE_FETCH_FAIL = "MESSAGE_FETCH_FAIL";
